### ISSUE TITLE
Hapi 8 compatibility

### ISSUE THREAD

**Issue by achingbrain** [wraithgar/moonboots_hapi#35]
Is there a way to get this module to work with Hapi 8?

The example from the readme has this:

```javascript
server.pack.require({moonboots_hapi: config}, function (er) {
    server.start();
});
```

..but I don't think `server.pack` exists any more.  I got a bit further with:

```javascript
server.register({register:require('moonboots_hapi'), options:config}, function (er) {
    ...
});
```

..but must have missed something as although the server started up without error, hitting the app page left me with a blank screen.

**Comment by wraithgar** [comment]
Hapi 8 support was added last month in version 4.0.0: https://github.com/wraithgar/moonboots_hapi/pull/34

Looks like I didn't update the readme though.

**Comment by wraithgar** [comment]
Ok I updated the readme and server.js example and release as 4.0.1.  Sorry for the confusion I hope you get things working now.  Keep me updated if you run into any more problems.

**Comment by achingbrain** [comment]
Much clearer now, thanks!
