### ISSUE TITLE
Is there interest in being a bit more windows platform smoothness ?

### ISSUE THREAD

**Issue by rluiten** [wraithgar/moonboots_hapi#36]
Firstly this is a nice little example project thank you.

On windows platform make is not something you can just depend on being available it can be non trivial to get one going if you have no prior experience with it. To lower the bar for windows platform it is very little effort to remove make as a dependency completely as what it is doing in this project is trivial.

I can create a pull request if you would like.

**Comment by wraithgar** [comment]
That sounds like a fine idea.
