### ISSUE TITLE
moonboots dependency is ^3.0.0?

### ISSUE THREAD

**Issue by gdibble** [wraithgar/moonboots_hapi#42]
why not ^4.0.2

**Comment by gdibble** [comment]
i have to ask for one simple reason.

i noticed tonight that when moonboots minifies my CSS (in `developmentMode:fase`), the ' ' space before and after the plus symbol within `calc` gets stripped away - thus: `width:calc(100%+150px)`. Unfortunately, this minified version breaks Chrome/webkit (w/ Chrome v42) and calc does not work without the spaces, therefore only this works: `width:calc(100% + 150px)`. It's a sad browser bug, however I was hoping to try a moonboots update (in hopes of a underlying minifying module update) to maybe-maybe help. i suspect that an update won't help with this particular minified CSS issue, but i wanted to try jic.

**Comment by gdibble** [comment]
ah ha! so i threw caution to the wind, updated moonboots dependency to ^4.0.1 in the package.json file and tested it. moonboots seems to be working fine, no errors and JS/CSS minified.

better news is that INDEED the update solved the CSS calc minification issue - now minified CSS is returned with the spaces - thus working: `width:calc(100% + 150px)`

moonboots dep update :+1:

**Comment by wraithgar** [comment]
I would suspect it's simply cause nobody has proposed to bump the dependency version.

**Comment by gdibble** [comment]
:dancer: [suggested](https://github.com/wraithgar/moonboots_hapi/pull/43) ;)
